name: test manual run with input
on:
  workflow_dispatch:
    inputs:
      RSPlus:
        description: 'Start build in RS+'
        required: true
        default: true
        type: boolean
      RS2:
        description: 'Start build in RS2'
        required: true
        default: 'false'
        type: boolean
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Script name: ${{ github.event.inputs.name }}"
          echo "Script path: ${{ github.event.inputs.path }}"